export const FETCH_TODAYS_GAMES = "FETCH_TODAYS_GAMES";
export const LOADING_TODAYS_GAMES = "LOADING_TODAYS_GAMES";
export const FETCH_PLAYERS = "FETCH_PLAYERS";
export const FETCH_UPCOMING_GAMES = "FETCH_UPCOMING_GAMES";
